#!/usr/bin/env python2

# Copyright (C) 2014  Jim Turner

# This file is part of raspbian_gpio_poweroffd.

# raspbian_gpio_poweroffd is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 2 of the License, or (at your option) any
# later version.

# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.  See the GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <http://www.gnu.org/licenses/>.

import logging
import logging.handlers
import os
import RPi.GPIO as GPIO
import subprocess
import sys
import time


console_format = '%(name)-13s %(levelname)-8s %(message)s'
syslog_format = 'thinkpad-scripts: %(name)s %(levelname)s %(message)s'


def daemonize():
    """
    Daemonize process, from http://www.jejik.com/articles/2007/02/a_simple_unix_linux_daemon_in_python/
    """
    try:
        pid = os.fork()
        if pid > 0:
            # exit first parent
            sys.exit(0)
    except OSError, e:
        sys.stderr.write("fork #1 failed: %d (%s)\n" % (e.errno, e.strerror))
        sys.exit(1)

    # decouple from parent environment
    os.chdir("/")
    os.setsid()
    os.umask(0)

    # do second fork
    try:
        pid = os.fork()
        if pid > 0:
            # exit from second parent
            sys.exit(0)
    except OSError, e:
        sys.stderr.write("fork #2 failed: %d (%s)\n" % (e.errno, e.strerror))
        sys.exit(1)

    # redirect standard file descriptors
    sys.stdout.flush()
    sys.stderr.flush()
    si = file('/dev/null', 'r')
    so = file('/dev/null', 'a+')
    se = file('/dev/null', 'a+', 0)
    os.dup2(si.fileno(), sys.stdin.fileno())
    os.dup2(so.fileno(), sys.stdout.fileno())
    os.dup2(se.fileno(), sys.stderr.fileno())


def setup_GPIO(channel):
    """Setup GPIO to read from specified channel.

    :param channel: GPIO channel number (board notation)
    """
    GPIO.setmode(GPIO.BOARD)
    GPIO.setwarnings(False)
    GPIO.setup(channel, GPIO.IN)


def setup_logging():
    """Setup logging to use system logger.

    :return: this module's Logger instance
    """
    logging.basicConfig(level=logging.INFO, format=console_format)
    syslog = logging.handlers.SysLogHandler(address='/dev/log')
    syslog.setLevel(logging.DEBUG)
    syslog.setFormatter(logging.Formatter(syslog_format))
    logging.getLogger().addHandler(syslog)
    return logging.getLogger(__name__)


def main(channel, hold_time):
    """Listen for `channel` to go to False. If it remains False for at
    least `hold_time`, then run ``poweroff``.

    :param channel: GPIO channel number (board notation)
    :param hold_time: hold time in seconds
    """
    setup_GPIO(channel)
    logger = setup_logging()
    while True:
        GPIO.wait_for_edge(channel, GPIO.FALLING)
        logging.debug('Caught button press.')
        press = time.time()
        while (time.time() - press) < hold_time:
            time.sleep(0.05)
            if GPIO.input(channel):
                logging.debug('Button released before {} seconds '
                              'elapsed.'.format(hold_time))
                break
        else:
            logger.info('Calling poweroff.')
            subprocess.Popen(['poweroff'])


if __name__ == '__main__':
    daemonize()
    main(3, 5)
